In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv("50_Startups.csv")

In [3]:
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,4].values

In [4]:
x

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [5]:
y

array([ 192261.83,  191792.06,  191050.39,  182901.99,  166187.94,
        156991.12,  156122.51,  155752.6 ,  152211.77,  149759.96,
        146121.95,  144259.4 ,  141585.52,  134307.35,  132602.65,
        129917.04,  126992.93,  125370.37,  124266.9 ,  122776.86,
        118474.03,  111313.02,  110352.25,  108733.99,  108552.04,
        107404.34,  105733.54,  105008.31,  103282.38,  101004.64,
         99937.59,   97483.56,   97427.84,   96778.92,   96712.8 ,
         96479.51,   90708.19,   89949.14,   81229.06,   81005.76,
         78239.91,   77798.83,   71498.49,   69758.98,   65200.33,
         64926.08,   49490.75,   42559.73,   35673.41,   14681.4 ])

In [6]:
# Encoding categorical data

from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [7]:
labelencoder_x = LabelEncoder()
x[:,3] = labelencoder_x.fit_transform(x[:,3])

# Enter the index number of the categorical column

onehotencoder = OneHotEncoder(categorical_features=[3])
x = onehotencoder.fit_transform(x).toarray()

In [8]:
np.set_printoptions(formatter={'float_kind':'{:f}'.format})
x

array([[0.000000, 0.000000, 1.000000, 165349.200000, 136897.800000,
        471784.100000],
       [1.000000, 0.000000, 0.000000, 162597.700000, 151377.590000,
        443898.530000],
       [0.000000, 1.000000, 0.000000, 153441.510000, 101145.550000,
        407934.540000],
       [0.000000, 0.000000, 1.000000, 144372.410000, 118671.850000,
        383199.620000],
       [0.000000, 1.000000, 0.000000, 142107.340000, 91391.770000,
        366168.420000],
       [0.000000, 0.000000, 1.000000, 131876.900000, 99814.710000,
        362861.360000],
       [1.000000, 0.000000, 0.000000, 134615.460000, 147198.870000,
        127716.820000],
       [0.000000, 1.000000, 0.000000, 130298.130000, 145530.060000,
        323876.680000],
       [0.000000, 0.000000, 1.000000, 120542.520000, 148718.950000,
        311613.290000],
       [1.000000, 0.000000, 0.000000, 123334.880000, 108679.170000,
        304981.620000],
       [0.000000, 1.000000, 0.000000, 101913.080000, 110594.110000,
        229160

In [9]:
# Avoiding dumy variable trap
x = x[:, 1:]

In [10]:
x

array([[0.000000, 1.000000, 165349.200000, 136897.800000, 471784.100000],
       [0.000000, 0.000000, 162597.700000, 151377.590000, 443898.530000],
       [1.000000, 0.000000, 153441.510000, 101145.550000, 407934.540000],
       [0.000000, 1.000000, 144372.410000, 118671.850000, 383199.620000],
       [1.000000, 0.000000, 142107.340000, 91391.770000, 366168.420000],
       [0.000000, 1.000000, 131876.900000, 99814.710000, 362861.360000],
       [0.000000, 0.000000, 134615.460000, 147198.870000, 127716.820000],
       [1.000000, 0.000000, 130298.130000, 145530.060000, 323876.680000],
       [0.000000, 1.000000, 120542.520000, 148718.950000, 311613.290000],
       [0.000000, 0.000000, 123334.880000, 108679.170000, 304981.620000],
       [1.000000, 0.000000, 101913.080000, 110594.110000, 229160.950000],
       [0.000000, 0.000000, 100671.960000, 91790.610000, 249744.550000],
       [1.000000, 0.000000, 93863.750000, 127320.380000, 249839.440000],
       [0.000000, 0.000000, 91992.390000, 

In [11]:
# Splitting the dataset into the test and training sets

from sklearn.cross_validation import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

C:\Users\Prabin\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [12]:
x_train

array([[1.000000, 0.000000, 55493.950000, 103057.490000, 214634.810000],
       [0.000000, 1.000000, 46014.020000, 85047.440000, 205517.640000],
       [1.000000, 0.000000, 75328.870000, 144135.980000, 134050.070000],
       [0.000000, 0.000000, 46426.070000, 157693.920000, 210797.670000],
       [1.000000, 0.000000, 91749.160000, 114175.790000, 294919.570000],
       [1.000000, 0.000000, 130298.130000, 145530.060000, 323876.680000],
       [1.000000, 0.000000, 119943.240000, 156547.420000, 256512.920000],
       [0.000000, 1.000000, 1000.230000, 124153.040000, 1903.930000],
       [0.000000, 1.000000, 542.050000, 51743.150000, 0.000000],
       [0.000000, 1.000000, 65605.480000, 153032.060000, 107138.380000],
       [0.000000, 1.000000, 114523.610000, 122616.840000, 261776.230000],
       [1.000000, 0.000000, 61994.480000, 115641.280000, 91131.240000],
       [0.000000, 0.000000, 63408.860000, 129219.610000, 46085.250000],
       [0.000000, 0.000000, 78013.110000, 121597.550000, 26434

In [13]:
x_test

array([[1.000000, 0.000000, 66051.520000, 182645.560000, 118148.200000],
       [0.000000, 0.000000, 100671.960000, 91790.610000, 249744.550000],
       [1.000000, 0.000000, 101913.080000, 110594.110000, 229160.950000],
       [1.000000, 0.000000, 27892.920000, 84710.770000, 164470.710000],
       [1.000000, 0.000000, 153441.510000, 101145.550000, 407934.540000],
       [0.000000, 1.000000, 72107.600000, 127864.550000, 353183.810000],
       [0.000000, 1.000000, 20229.590000, 65947.930000, 185265.100000],
       [0.000000, 1.000000, 61136.380000, 152701.920000, 88218.230000],
       [1.000000, 0.000000, 73994.560000, 122782.750000, 303319.260000],
       [1.000000, 0.000000, 142107.340000, 91391.770000, 366168.420000]])

In [14]:
# Fitting the training set

from sklearn.linear_model import LinearRegression

In [15]:
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [16]:
# Make the prediction

y_pred = regressor.predict(x_test)

In [17]:
y_pred

array([103015.201598, 132582.277608, 132447.738452, 71976.098513,
       178537.482211, 116161.242302, 67851.692097, 98791.733747,
       113969.435330, 167921.065696])

In [18]:
y_test

array([103282.380000, 144259.400000, 146121.950000, 77798.830000,
       191050.390000, 105008.310000, 81229.060000, 97483.560000,
       110352.250000, 166187.940000])

In [19]:
# Backward Elimination

import statsmodels.formula.api as sm

# According to the formula b0 + b1 * x1 + b2 * x2 + ...
# In LinearRegression we don't need to set b0 but in the state model we have to set
# b0 and that's way we gonna use np.ones() to create an array with 1's and we want that
# array to append at the beginning of the array so that's way the below line was use

x = np.append(arr=np.ones((50, 1)).astype(int), values=x, axis=1)