In [22]:
import pandas as pd
import numpy as np

In [23]:
dataset = pd.read_csv("50_Startups.csv")

In [24]:
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,4].values

In [25]:
x

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [26]:
y

array([192261.830000, 191792.060000, 191050.390000, 182901.990000,
       166187.940000, 156991.120000, 156122.510000, 155752.600000,
       152211.770000, 149759.960000, 146121.950000, 144259.400000,
       141585.520000, 134307.350000, 132602.650000, 129917.040000,
       126992.930000, 125370.370000, 124266.900000, 122776.860000,
       118474.030000, 111313.020000, 110352.250000, 108733.990000,
       108552.040000, 107404.340000, 105733.540000, 105008.310000,
       103282.380000, 101004.640000, 99937.590000, 97483.560000,
       97427.840000, 96778.920000, 96712.800000, 96479.510000,
       90708.190000, 89949.140000, 81229.060000, 81005.760000,
       78239.910000, 77798.830000, 71498.490000, 69758.980000,
       65200.330000, 64926.080000, 49490.750000, 42559.730000,
       35673.410000, 14681.400000])

In [27]:
# Encoding categorical data

from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [28]:
labelencoder_x = LabelEncoder()
x[:,3] = labelencoder_x.fit_transform(x[:,3])

# Enter the index number of the categorical column

onehotencoder = OneHotEncoder(categorical_features=[3])
x = onehotencoder.fit_transform(x).toarray()

In [29]:
np.set_printoptions(formatter={'float_kind':'{:f}'.format})
x

array([[0.000000, 0.000000, 1.000000, 165349.200000, 136897.800000,
        471784.100000],
       [1.000000, 0.000000, 0.000000, 162597.700000, 151377.590000,
        443898.530000],
       [0.000000, 1.000000, 0.000000, 153441.510000, 101145.550000,
        407934.540000],
       [0.000000, 0.000000, 1.000000, 144372.410000, 118671.850000,
        383199.620000],
       [0.000000, 1.000000, 0.000000, 142107.340000, 91391.770000,
        366168.420000],
       [0.000000, 0.000000, 1.000000, 131876.900000, 99814.710000,
        362861.360000],
       [1.000000, 0.000000, 0.000000, 134615.460000, 147198.870000,
        127716.820000],
       [0.000000, 1.000000, 0.000000, 130298.130000, 145530.060000,
        323876.680000],
       [0.000000, 0.000000, 1.000000, 120542.520000, 148718.950000,
        311613.290000],
       [1.000000, 0.000000, 0.000000, 123334.880000, 108679.170000,
        304981.620000],
       [0.000000, 1.000000, 0.000000, 101913.080000, 110594.110000,
        229160

In [30]:
# Avoiding dumy variable trap
x = x[:, 1:]

In [31]:
x

array([[0.000000, 1.000000, 165349.200000, 136897.800000, 471784.100000],
       [0.000000, 0.000000, 162597.700000, 151377.590000, 443898.530000],
       [1.000000, 0.000000, 153441.510000, 101145.550000, 407934.540000],
       [0.000000, 1.000000, 144372.410000, 118671.850000, 383199.620000],
       [1.000000, 0.000000, 142107.340000, 91391.770000, 366168.420000],
       [0.000000, 1.000000, 131876.900000, 99814.710000, 362861.360000],
       [0.000000, 0.000000, 134615.460000, 147198.870000, 127716.820000],
       [1.000000, 0.000000, 130298.130000, 145530.060000, 323876.680000],
       [0.000000, 1.000000, 120542.520000, 148718.950000, 311613.290000],
       [0.000000, 0.000000, 123334.880000, 108679.170000, 304981.620000],
       [1.000000, 0.000000, 101913.080000, 110594.110000, 229160.950000],
       [0.000000, 0.000000, 100671.960000, 91790.610000, 249744.550000],
       [1.000000, 0.000000, 93863.750000, 127320.380000, 249839.440000],
       [0.000000, 0.000000, 91992.390000, 

In [32]:
# Splitting the dataset into the test and training sets

from sklearn.cross_validation import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [33]:
x_train

array([[1.000000, 0.000000, 55493.950000, 103057.490000, 214634.810000],
       [0.000000, 1.000000, 46014.020000, 85047.440000, 205517.640000],
       [1.000000, 0.000000, 75328.870000, 144135.980000, 134050.070000],
       [0.000000, 0.000000, 46426.070000, 157693.920000, 210797.670000],
       [1.000000, 0.000000, 91749.160000, 114175.790000, 294919.570000],
       [1.000000, 0.000000, 130298.130000, 145530.060000, 323876.680000],
       [1.000000, 0.000000, 119943.240000, 156547.420000, 256512.920000],
       [0.000000, 1.000000, 1000.230000, 124153.040000, 1903.930000],
       [0.000000, 1.000000, 542.050000, 51743.150000, 0.000000],
       [0.000000, 1.000000, 65605.480000, 153032.060000, 107138.380000],
       [0.000000, 1.000000, 114523.610000, 122616.840000, 261776.230000],
       [1.000000, 0.000000, 61994.480000, 115641.280000, 91131.240000],
       [0.000000, 0.000000, 63408.860000, 129219.610000, 46085.250000],
       [0.000000, 0.000000, 78013.110000, 121597.550000, 26434

In [34]:
x_test

array([[1.000000, 0.000000, 66051.520000, 182645.560000, 118148.200000],
       [0.000000, 0.000000, 100671.960000, 91790.610000, 249744.550000],
       [1.000000, 0.000000, 101913.080000, 110594.110000, 229160.950000],
       [1.000000, 0.000000, 27892.920000, 84710.770000, 164470.710000],
       [1.000000, 0.000000, 153441.510000, 101145.550000, 407934.540000],
       [0.000000, 1.000000, 72107.600000, 127864.550000, 353183.810000],
       [0.000000, 1.000000, 20229.590000, 65947.930000, 185265.100000],
       [0.000000, 1.000000, 61136.380000, 152701.920000, 88218.230000],
       [1.000000, 0.000000, 73994.560000, 122782.750000, 303319.260000],
       [1.000000, 0.000000, 142107.340000, 91391.770000, 366168.420000]])

In [35]:
# Fitting the training set

from sklearn.linear_model import LinearRegression

In [36]:
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [37]:
# Make the prediction

y_pred = regressor.predict(x_test)

In [38]:
y_pred

array([103015.201598, 132582.277608, 132447.738452, 71976.098513,
       178537.482211, 116161.242302, 67851.692097, 98791.733747,
       113969.435330, 167921.065696])

In [39]:
y_test

array([103282.380000, 144259.400000, 146121.950000, 77798.830000,
       191050.390000, 105008.310000, 81229.060000, 97483.560000,
       110352.250000, 166187.940000])

## Backward Elimination

In [40]:
# Backward Elimination

import statsmodels.formula.api as sm

# According to the formula b0 + b1 * x1 + b2 * x2 + ...
# In LinearRegression we don't need to set b0 but in the state model we have to set
# b0 and that's way we gonna use np.ones() to create an array with 1's and we want that
# array to append at the beginning of the array so that's way the below line was use

x = np.append(arr=np.ones((50, 1)).astype(int), values=x, axis=1)

In [44]:
x_opt = x[:, [0,1,2,3,4,5]]

In [45]:
regressor_OLS = sm.OLS(endog=y, exog=x_opt).fit()

In [46]:
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Sat, 10 Feb 2018   Prob (F-statistic):           1.34e-27
Time:                        00:52:30   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.013e+04   6884.820      7.281      0.000    3.62e+04     6.4e+04
x1           198.7888   3371.007      0.059      0.953   -6595.030    6992.607
x2           -41.8870   3256.039     -0.013      0.990   -6604.003    6520.229
x3             0.8060      0.046     17.369      0.000       0.712       0.900
x4            -0.0270      0.052     -0.517      0.608      -0.132       0.078
x5             0.0270      0.017      1.574      0.123      -0.008       0.062
==============================================================================
Omnibus:                       14.782   Durbin-Watson:                   1.283
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.266
Skew:                          -0.948   Prob(JB):                     2.41e-05
Kurtosis:                       5.572   Cond. No.                     1.45e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.45e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [47]:
# Remove the constant with the highest p values and fit the model without
# the constant
# Repeat the steps until P > SL (SL = 0.05)

x_opt = x[:, [0,1,3,4,5]]
regressor_OLS = sm.OLS(endog=y, exog=x_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     217.2
Date:                Sat, 10 Feb 2018   Prob (F-statistic):           8.49e-29
Time:                        00:59:36   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1070.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.011e+04   6647.870      7.537      0.000    3.67e+04    6.35e+04
x1           220.1585   2900.536      0.076      0.940   -5621.821    6062.138
x2             0.8060      0.046     17.606      0.000       0.714       0.898
x3            -0.0270      0.052     -0.523      0.604      -0.131       0.077
x4             0.0270      0.017      1.592      0.118      -0.007       0.061
==============================================================================
Omnibus:                       14.758   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.172
Skew:                          -0.948   Prob(JB):                     2.53e-05
Kurtosis:                       5.563   Cond. No.                     1.40e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [48]:
x_opt = x[:, [0,3,4,5]]
regressor_OLS = sm.OLS(endog=y, exog=x_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     296.0
Date:                Sat, 10 Feb 2018   Prob (F-statistic):           4.53e-30
Time:                        07:33:11   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      46   BIC:                             1066.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.012e+04   6572.353      7.626      0.000    3.69e+04    6.34e+04
x1             0.8057      0.045     17.846      0.000       0.715       0.897
x2            -0.0268      0.051     -0.526      0.602      -0.130       0.076
x3             0.0272      0.016      1.655      0.105      -0.006       0.060
==============================================================================
Omnibus:                       14.838   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.442
Skew:                          -0.949   Prob(JB):                     2.21e-05
Kurtosis:                       5.586   Cond. No.                     1.40e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [49]:
x_opt = x[:, [0,3,5]]
regressor_OLS = sm.OLS(endog=y, exog=x_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Sat, 10 Feb 2018   Prob (F-statistic):           2.16e-31
Time:                        07:35:25   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.698e+04   2689.933     17.464      0.000    4.16e+04    5.24e+04
x1             0.7966      0.041     19.266      0.000       0.713       0.880
x2             0.0299      0.016      1.927      0.060      -0.001       0.061
==============================================================================
Omnibus:                       14.677   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.161
Skew:                          -0.939   Prob(JB):                     2.54e-05
Kurtosis:                       5.575   Cond. No.                     5.32e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.32e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""